name: Push Changes to GitHub

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of Commiter'
        required: false
        default: 'github-actions'
      email:
        description: 'Email of Commiter'
        required: false
        default: 'github-actions@github.com'
      message:
        description: 'Commit Message'
        required: false
        default: 'github actions generated commit'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Push changes to GitHub
        run: |
          date > generated.txt
          git config user.name ${{ github.event.inputs.name }}
          git config user.email ${{ github.event.inputs.email }}
          git add .
          git commit -m ${{ github.event.inputs.message }}
          git push
