name: Docker Build and Push

on:
  workflow_call:
    inputs:
      # Repository name
      dockerhub_repo_name:
        required: true
        type: string
      # Platforms to build for
      platforms:
        required: false
        type: string
        default: linux/amd64
      # Image tag
      image_tag:
        required: false
        type: string
        default: latest
      # Whether to push the image to DockerHub
      should_push:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_PASSWORD:
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ env.DOCKER_USERNAME != null && env.DOCKER_PASSWORD != null }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ inputs.image_tag }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ inputs.should_push && env.DOCKER_USERNAME != null && env.DOCKER_PASSWORD != null }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
