name: Python Black Formatter

on:
  workflow_call:
    inputs:
      black_command:
        type: string
        required: false
        default: 'black .'

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Format with Black
        run: |
          python -m pip install --upgrade pip
          pip install black
          ${{ github.event.inputs.black_command }}
      -
        name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes"
            exit 1
          fi
      -
        name: Push changes to GitHub
        if: steps.check_changes.outcome == 'success'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-format with Black"
          git push
