name: Python Black Formatter

on:
  workflow_call:
    inputs:
      command:
        type: string
        required: false
        default: 'black .'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Format with Black
        run: |
          python -m pip install --upgrade pip
          pip install black
          ${{ github.event.inputs.command }}
      -
        name: Push changes to GitHub
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-format with Black"
          git push
