name: Python isort Formatter

on:
  workflow_call:
    inputs:
      isort_command:
        description: 'The isort command to run'
        type: string
        required: false
        default: 'isort .'

jobs:
  isort:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Sort imports
        run: |
          python -m pip install --upgrade pip
          pip install isort
          ${{ github.event.inputs.isort_command }}
      -
        name: Remove unused imports
        run: |
          python -m pip install --upgrade pip
          pip install autoflake
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .
      -
        name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes"
            echo "changes=0" >> $GITHUB_ENV
          else
            echo "Changes found"
            echo "changes=1" >> $GITHUB_ENV
          fi
      -
        name: Push changes to GitHub
        if: steps.check_changes.outputs.changes == '1'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Apply isort and autoflake"
          git push
