name: GitHub Security Workflow

on:
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Run Zizmor
        uses: zizmorcore/zizmor-action@c65bc8876171b6d82748ec98b77c0193b1226b94
        with:
          persona: "auditor"
